name: Azure ARM
on: 
  push:
    branches: 
      - main
      
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./IoTEdgeDeploymentApi/Deployment/azuredeploy.json
          parameters: ./IoTEdgeDeploymentApi/Deployment/azuredeploy.parameters.json ioTHubConString=${{ secrets.IOTHUB_CONSTRING }}-overriden storageAccountName=${{ secrets.STORAGEACCOUNT_NAME }}-overriden appInsightsName=${{ secrets.APPINSIGHTS_NAME }}-overriden azureFuncName=${{ secrets.AZUREFUNC_NAME }}-overriden hostingPlanName=${{ secrets.HOSTINGPLAN_NAME }}-overriden
